 # Tugas 7 : Klasifikasi Berita Metode Logistic Regression dengan reduksi dimensi (SVD)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

df = pd.read_csv("/content/drive/My Drive/ppw/report/tugas-ppw/hasil_prepros.csv")
df.head()

,judul,tanggal,isi,kategori,cleansing,case_folding,tokenize,stopword_removal
0,Gejala Sifilis pada Wanita Berdasarkan Tahapan...,"Rabu, 16 Okt 2024 21:00 WIB",Jakarta - Sifilis atau penyakit raja singa ter...,Kesehatan,Jakarta Sifilis atau penyakit raja singa term...,jakarta sifilis atau penyakit raja singa term...,"['jakarta', 'sifilis', 'atau', 'penyakit', 'ra...",jakarta sifilis penyakit raja singa infeksi me...
1,Puncak Nafsu Pria Ada di Umur Berapa? Studi Bi...,"Rabu, 16 Okt 2024 20:02 WIB",Jakarta - Sebagian orang pasti sudah mengenal ...,Kesehatan,Jakarta Sebagian orang pasti sudah mengenal i...,jakarta sebagian orang pasti sudah mengenal i...,"['jakarta', 'sebagian', 'orang', 'pasti', 'sud...",jakarta orang mengenal istilah puncak seksual ...
2,"Gejala Kanker Mulut yang Kerap Tak Disadari, T...","Rabu, 16 Okt 2024 18:02 WIB",Jakarta - Setiap orang mungkin pernah mengalam...,Kesehatan,Jakarta Setiap orang mungkin pernah mengalami...,jakarta setiap orang mungkin pernah mengalami...,"['jakarta', 'setiap', 'orang', 'mungkin', 'per...",jakarta orang mengalami sariawan luka mulut me...
3,Kapan Waktu yang Tepat untuk Minum Air Rebusan...,"Rabu, 16 Okt 2024 17:31 WIB",Jakarta - Air rebusan serai dikenal sebagai sa...,Kesehatan,Jakarta Air rebusan serai dikenal sebagai sal...,jakarta air rebusan serai dikenal sebagai sal...,"['jakarta', 'air', 'rebusan', 'serai', 'dikena...",jakarta air rebusan serai dikenal salah ramuan...
4,Viral Hanni NewJeans Bicara soal Bullying di T...,"Rabu, 16 Okt 2024 16:34 WIB","Jakarta - Viral momen member NewJeans, Hanni, ...",Kesehatan,Jakarta Viral momen member NewJeans Hanni ber...,jakarta viral momen member newjeans hanni ber...,"['jakarta', 'viral', 'momen', 'member', 'newje...",jakarta viral momen member newjeans hanni berb...

Label Encoder

In [ ]:
from sklearn.preprocessing import LabelEncoder

# Transformasi data kategorik
label_encoder = LabelEncoder()
df.loc[:, 'kategori_encoded'] = label_encoder.fit_transform(df['kategori'])

# Menampilkan nilai sebelum dan sesudah konversi
print("\nNilai sebelum dan sesudah konversi:")
print(dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_))))

print("\nDataFrame setelah Label Encoding:")
df.head()

Nilai sebelum dan sesudah konversi:
{'Kesehatan': 0, 'Olahraga': 1}

DataFrame setelah Label Encoding:

,judul,tanggal,isi,kategori,cleansing,case_folding,tokenize,stopword_removal,kategori_encoded
0,Gejala Sifilis pada Wanita Berdasarkan Tahapan...,"Rabu, 16 Okt 2024 21:00 WIB",Jakarta - Sifilis atau penyakit raja singa ter...,Kesehatan,Jakarta Sifilis atau penyakit raja singa term...,jakarta sifilis atau penyakit raja singa term...,"['jakarta', 'sifilis', 'atau', 'penyakit', 'ra...",jakarta sifilis penyakit raja singa infeksi me...,0
1,Puncak Nafsu Pria Ada di Umur Berapa? Studi Bi...,"Rabu, 16 Okt 2024 20:02 WIB",Jakarta - Sebagian orang pasti sudah mengenal ...,Kesehatan,Jakarta Sebagian orang pasti sudah mengenal i...,jakarta sebagian orang pasti sudah mengenal i...,"['jakarta', 'sebagian', 'orang', 'pasti', 'sud...",jakarta orang mengenal istilah puncak seksual ...,0
2,"Gejala Kanker Mulut yang Kerap Tak Disadari, T...","Rabu, 16 Okt 2024 18:02 WIB",Jakarta - Setiap orang mungkin pernah mengalam...,Kesehatan,Jakarta Setiap orang mungkin pernah mengalami...,jakarta setiap orang mungkin pernah mengalami...,"['jakarta', 'setiap', 'orang', 'mungkin', 'per...",jakarta orang mengalami sariawan luka mulut me...,0
3,Kapan Waktu yang Tepat untuk Minum Air Rebusan...,"Rabu, 16 Okt 2024 17:31 WIB",Jakarta - Air rebusan serai dikenal sebagai sa...,Kesehatan,Jakarta Air rebusan serai dikenal sebagai sal...,jakarta air rebusan serai dikenal sebagai sal...,"['jakarta', 'air', 'rebusan', 'serai', 'dikena...",jakarta air rebusan serai dikenal salah ramuan...,0
4,Viral Hanni NewJeans Bicara soal Bullying di T...,"Rabu, 16 Okt 2024 16:34 WIB","Jakarta - Viral momen member NewJeans, Hanni, ...",Kesehatan,Jakarta Viral momen member NewJeans Hanni ber...,jakarta viral momen member newjeans hanni ber...,"['jakarta', 'viral', 'momen', 'member', 'newje...",jakarta viral momen member newjeans hanni berb...,0

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score

In [ ]:
# Memisahkan fitur dan label
x = df['stopword_removal']
y = df['kategori_encoded']

In [ ]:
# Membagi data menjadi data latih dan data uji
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [ ]:
# Tahap 1: TF-IDF
tfidf_vectorizer = TfidfVectorizer()
x_train_tfidf = tfidf_vectorizer.fit_transform(x_train)
x_test_tfidf = tfidf_vectorizer.transform(x_test)

# Mengonversi hasil TF-IDF menjadi DataFrame
df_train_tfidf = pd.DataFrame(x_train_tfidf.toarray(), columns=tfidf_vectorizer.get_feature_names_out())
df_test_tfidf = pd.DataFrame(x_test_tfidf.toarray(), columns=tfidf_vectorizer.get_feature_names_out())
print("Hasil TF-IDF (Data Latih):")
df_train_tfidf

Hasil TF-IDF (Data Latih):

,abadi,abc,abdalla,abdullah,abnormal,aboy,absen,abuabu,acar,acara,...,zaitun,zaki,zarco,zat,zerlinda,zhehuang,zhen,zi,zona,zu
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.031282,0.0,0.057168,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
76,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,...,0.0,0.0,0.139933,0.0,0.0,0.0,0.0,0.0,0.0,0.0
77,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
78,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
79,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
# Tahap 2: SVD (Reduksi Dimensi)
svd = TruncatedSVD(n_components=100, random_state=42)
x_train_svd = svd.fit_transform(x_train_tfidf)
x_test_svd = svd.transform(x_test_tfidf)

# Mengonversi hasil SVD menjadi DataFrame
df_train_svd = pd.DataFrame(x_train_svd)
df_test_svd = pd.DataFrame(x_test_svd)
print("\nHasil SVD (Data Latih):")
df_train_svd

Hasil SVD (Data Latih):

,0,1,2,3,4,5,6,7,8,9,...,70,71,72,73,74,75,76,77,78,79
0,0.297978,-0.068349,0.005871,-0.025223,0.017418,-0.248632,-0.064474,0.026051,0.040062,0.045852,...,-0.178332,0.071672,0.069838,0.083811,-0.218284,-0.127426,0.004652,0.048237,0.000226,-0.001124
1,0.071974,0.061516,0.266571,-0.040754,0.027362,0.080957,0.376574,-0.019294,0.737504,-0.004255,...,0.041111,-0.000571,0.013142,0.000068,-0.000628,0.008185,0.407019,-0.003304,-0.004336,0.001674
2,0.020671,0.125250,0.003469,0.030713,0.300477,0.007176,-0.064805,-0.191421,-0.000028,-0.092407,...,0.009898,0.010413,-0.005441,-0.003833,-0.000269,0.001512,-0.002425,-0.000749,0.001183,0.004225
3,0.028059,0.157170,-0.002992,0.046441,0.356649,-0.002015,-0.100097,-0.250411,0.007628,-0.135242,...,0.006998,0.000297,0.003324,-0.007626,0.005151,-0.004845,-0.001449,0.002353,-0.001301,-0.004962
4,0.062655,0.205396,-0.046399,-0.052738,-0.062294,-0.019352,0.071533,0.004643,-0.020540,-0.150012,...,0.015999,-0.010793,-0.007334,0.020844,0.022576,-0.019150,0.002913,-0.000916,-0.000666,0.001351
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.067594,0.045119,0.068210,0.031530,0.035900,0.022195,0.125031,0.010053,0.115894,0.007413,...,-0.015775,0.000526,0.000433,-0.000330,-0.013345,-0.001969,-0.045412,-0.012145,-0.000688,0.004969
76,0.096516,0.113803,0.628581,-0.134912,-0.056185,-0.011018,-0.103214,0.024953,-0.079812,-0.025626,...,0.072258,-0.009697,-0.003746,0.032071,-0.005190,0.031821,0.044109,0.024945,-0.003520,0.001072
77,0.046364,0.292593,-0.058402,-0.076290,0.136157,-0.013544,-0.095881,-0.084409,0.058431,0.719808,...,-0.055820,-0.378799,0.188893,0.169036,0.058725,-0.014659,-0.002212,-0.020577,0.002506,-0.001922
78,0.131632,0.085080,0.559544,-0.094456,-0.049786,-0.067269,-0.159708,0.027003,-0.152302,0.013514,...,-0.098666,0.005944,-0.008767,-0.011091,0.008456,-0.012086,-0.006911,-0.038105,0.007923,-0.003392
79,0.390412,-0.074336,-0.000604,-0.024629,0.010500,-0.299089,-0.118992,0.036080,0.037440,-0.014562,...,0.003737,-0.024885,-0.059125,0.055505,-0.084181,0.092067,0.001008,0.054384,0.002436,-0.000329

In [ ]:
# Tahap 3: Klasifikasi dengan Logistic Regression
clf = LogisticRegression(C=0.2, random_state=42)
clf.fit(x_train_svd, y_train)
y_pred = clf.predict(x_test_svd)

In [ ]:
# Evaluasi Model
print("\nAccuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.95
              precision    recall  f1-score   support

           0       0.92      1.00      0.96        12
           1       1.00      0.88      0.93         8

    accuracy                           0.95        20
   macro avg       0.96      0.94      0.95        20
weighted avg       0.95      0.95      0.95        20

Pengujian

---

In [ ]:
import joblib
from sklearn.pipeline import Pipeline

# Misalnya, Anda telah membuat pipeline
pipeline = Pipeline([
    ('tfidf', TfidfVectorizer()),
    ('x_train_svd', TruncatedSVD(n_components=100)),
    ('clf', LogisticRegression())
])

# Setelah melatih model
pipeline.fit(x_train, y_train)

# Menyimpan pipeline
joblib.dump(pipeline, 'svd_tfidf_pipeline.pkl')

['svd_tfidf_pipeline.pkl']

In [ ]:
import joblib
from sklearn.pipeline import Pipeline

# Misalnya, Anda telah membuat pipeline
pipeline = Pipeline([
    ('tfidf', TfidfVectorizer()),
    ('x_train_svd', TruncatedSVD(n_components=100)),
    ('clf', LogisticRegression())
])

# Setelah melatih model
pipeline.fit(x_train, y_train)

# Menyimpan pipeline
joblib.dump(pipeline, 'svd_tfidf_pipeline.joblib')

['svd_tfidf_pipeline.joblib']

In [ ]:
import joblib
import pandas as pd

# Memuat pipeline yang telah disimpan
pipeline = joblib.load('svd_tfidf_pipeline.pkl')

# Teks baru yang ingin diprediksi
new_text_1 = ['''Wasit memiliki peran krusial dalam olahraga. Disebut sebagai pemimpin pertandingan, seorang wasit bertugas sebagai hakim yang menentukan kualitas adilnya sebuah kompetisi. Pentingnya sosok serta kredibilitas seorang wasit membuat setiap keputusannya menjadi sebuah sorotan.
Tidak jarang, wasit membuat keputusan kontroversial. Namun, seiring dengan perkembangan teknologi, keputusan wasit lebih dapat dipertanggungjawabkan. Dalam sepakbola misalnya, teknologi yang dikenal sebagai VAR (Video Assistant Referee) bukan hanya memperkuat keputusan wasit tetapi juga mengubahnya. Meski demikian, keputusan wasit selalu bersifat final.
Menyoal kontroversi yang dilakukan wasit, kejadian terbaru muncul dalam pertandingan Bournemouth vs Chelsea yang dilaksanakan pada Sabtu (14/9) lalu di Stadion Vitality. Kala itu, Wasit Anthony Taylor mengeluarkan 16 kartu kuning untuk masing-masing tim. Oleh karenanya, ia tidak lagi ditugaskan sebagai wasit di Premiere League.
Timnas Indonesia sendiri pernah merasa dirugikan oleh adanya wasit yang diduga 'nakal'. Hal ini terjadi saat Tim Garuda berlaga melawan Uzbekistan di Piala Asia U-23 2024. Kala itu, pertandingan ini dipimpin oleh wasit Shen Yinhao. Oleh karena beberapa keputusan yang dianggap kontroversial, namanya pun diburu oleh netizen Indonesia di media sosial.''']

new_text_2 = ['''Mengkonsumsi buah setiap hari dapat membantu tubuh tetap sehat. Meski mengandung vitamin dan nutrisi tinggi, tetapi tak semua buah aman dikonsumsi bagi pengidap asam lambung.
Sedikit informasi, asam lambung atau gastroesophageal reflux disease (GERD) adalah gangguan pencernaan yang salah satunya dipicu oleh makanan. Maka dari itu, pengidapnya harus hati-hati dalam memilih makanan untuk dikonsumsi, termasuk buah-buahan.
Buah yang mengandung kadar asam tinggi dianjurkan untuk tidak dikonsumsi bagi pengidap GERD. Lantas, apa saja buah yang aman dikonsumsi oleh pengidap asam lambung? Simak selengkapnya dalam artikel ini.
Buah yang Aman untuk Pengidap Asam Lambung
Ada sejumlah buah yang baik dikonsumsi untuk pengidap asam lambung. Mengutip situs Healthline dan Medical News Today, berikut daftar buahnya:
1. Pisang
Di daftar yang pertama ada pisang. Buah ini dipercaya dapat membantu mengatasi asam lambung naik. Sebab, pisang memiliki pH tinggi sehingga bersifat basa atau rendah asam.
Buah yang bersifat basa dapat membantu menetralisir cairan asam di lambung dengan cara melindungi lapisan esofagus yang teriritasi.
Lalu, pisang juga mengandung serat larut bernama pekting. Senyawa ini dapat membantu memproses makanan dengan baik di sistem pencernaan.''']

# Gabungkan kedua teks menjadi satu list
new_text = new_text_1 + new_text_2


# Melakukan prediksi dengan pipeline
predictions = pipeline.predict(new_text)

# Hasil prediksi
predicted_categories = ["Kesehatan" if predictions ==  0 else "Olahraga" for predictions in predictions]

# Output hasil prediksi untuk masing-masing teks
for i, category in enumerate(predicted_categories):
    print(f"Prediksi untuk teks {i+1}: {category}")

Prediksi untuk teks 1: Olahraga
Prediksi untuk teks 2: Kesehatan