# Tugas 6 : Sistem pencarian dokumen dengan penerapan Singular Value Decomposition (SVD)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

data_path = ("/content/drive/My Drive/ppw/report/tugas-ppw/hasil_prepros.csv")
news_data = pd.read_csv(data_path)

news_data

,judul,tanggal,isi,kategori,cleansing,case_folding,tokenize,stopword_removal
0,Gejala Sifilis pada Wanita Berdasarkan Tahapan...,"Rabu, 16 Okt 2024 21:00 WIB",Jakarta - Sifilis atau penyakit raja singa ter...,Kesehatan,Jakarta Sifilis atau penyakit raja singa term...,jakarta sifilis atau penyakit raja singa term...,"['jakarta', 'sifilis', 'atau', 'penyakit', 'ra...",jakarta sifilis penyakit raja singa infeksi me...
1,Puncak Nafsu Pria Ada di Umur Berapa? Studi Bi...,"Rabu, 16 Okt 2024 20:02 WIB",Jakarta - Sebagian orang pasti sudah mengenal ...,Kesehatan,Jakarta Sebagian orang pasti sudah mengenal i...,jakarta sebagian orang pasti sudah mengenal i...,"['jakarta', 'sebagian', 'orang', 'pasti', 'sud...",jakarta orang mengenal istilah puncak seksual ...
2,"Gejala Kanker Mulut yang Kerap Tak Disadari, T...","Rabu, 16 Okt 2024 18:02 WIB",Jakarta - Setiap orang mungkin pernah mengalam...,Kesehatan,Jakarta Setiap orang mungkin pernah mengalami...,jakarta setiap orang mungkin pernah mengalami...,"['jakarta', 'setiap', 'orang', 'mungkin', 'per...",jakarta orang mengalami sariawan luka mulut me...
3,Kapan Waktu yang Tepat untuk Minum Air Rebusan...,"Rabu, 16 Okt 2024 17:31 WIB",Jakarta - Air rebusan serai dikenal sebagai sa...,Kesehatan,Jakarta Air rebusan serai dikenal sebagai sal...,jakarta air rebusan serai dikenal sebagai sal...,"['jakarta', 'air', 'rebusan', 'serai', 'dikena...",jakarta air rebusan serai dikenal salah ramuan...
4,Viral Hanni NewJeans Bicara soal Bullying di T...,"Rabu, 16 Okt 2024 16:34 WIB","Jakarta - Viral momen member NewJeans, Hanni, ...",Kesehatan,Jakarta Viral momen member NewJeans Hanni ber...,jakarta viral momen member newjeans hanni ber...,"['jakarta', 'viral', 'momen', 'member', 'newje...",jakarta viral momen member newjeans hanni berb...
...,...,...,...,...,...,...,...,...
95,Jadwal-Klasemen MotoGP 2024: Martin Vs Bagnaia...,"Minggu, 13 Okt 2024 12:45 WIB",Jakarta - Simak di sini jadwal-klasemen MotoGP...,Olahraga,Jakarta Simak di sini jadwalklasemen MotoGP ...,jakarta simak di sini jadwalklasemen motogp ...,"['jakarta', 'simak', 'di', 'sini', 'jadwalklas...",jakarta simak jadwalklasemen motogp duel jorge...
96,Jadwal Final Arctic Open 2024: Ada Jonatan Chr...,"Minggu, 13 Okt 2024 11:15 WIB",Jakarta - Tunggal putra Jonatan Christie menja...,Olahraga,Jakarta Tunggal putra Jonatan Christie menjad...,jakarta tunggal putra jonatan christie menjad...,"['jakarta', 'tunggal', 'putra', 'jonatan', 'ch...",jakarta tunggal putra jonatan christie satusat...
97,GTWCE 2024: Sean Gelael dan Calan Williams Jag...,"Minggu, 13 Okt 2024 10:05 WIB",Barcelona - Sean Gelael memang datang dadakan ...,Olahraga,Barcelona Sean Gelael memang datang dadakan d...,barcelona sean gelael memang datang dadakan d...,"['barcelona', 'sean', 'gelael', 'memang', 'dat...",barcelona sean gelael dadakan ajang fanatec gt...
98,"Arctic Open 2024: Lawan Mundur, Jonatan Melaju...","Minggu, 13 Okt 2024 00:05 WIB",Vantaa - Jonatan Christie melaju ke final Arct...,Olahraga,Vantaa Jonatan Christie melaju ke final Arcti...,vantaa jonatan christie melaju ke final arcti...,"['vantaa', 'jonatan', 'christie', 'melaju', 'k...",vantaa jonatan christie melaju final arctic op...
99,11 Atlet Muda Raih Beasiswa Bulutangkis,"Sabtu, 12 Okt 2024 22:50 WIB",Kudus - 11 atlet muda berhasil meraih Beasiswa...,Olahraga,Kudus atlet muda berhasil meraih Beasiswa Bu...,kudus atlet muda berhasil meraih beasiswa bu...,"['kudus', 'atlet', 'muda', 'berhasil', 'meraih...",kudus atlet muda berhasil meraih beasiswa bulu...

In [ ]:
# Ambil kolom dokumen berita
documents = news_data['stopword_removal'].tolist()

**TF-IDF (Term Frequency-Inverse Document Frequency)**

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD
from sklearn.metrics.pairwise import euclidean_distances
import pandas as pd
import numpy as np
import joblib

In [ ]:
tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(documents)

# Mendapatkan fitur (kata-kata) dari TF-IDF
tfidf_features = tfidf_vectorizer.get_feature_names_out()

# Mengonversi matriks TF-IDF menjadi DataFrame
tfidf_df = pd.DataFrame(tfidf_matrix.toarray(), columns=tfidf_features)

# Tampilkan hasil TF-IDF
print("\nHasil TF-IDF dalam bentuk DataFrame:")
tfidf_df

Hasil TF-IDF dalam bentuk DataFrame:

,abadi,abc,abdalla,abdullah,abnormal,aboy,absen,abuabu,acar,acara,...,zaki,zarco,zat,zerlinda,zhang,zhehuang,zhen,zi,zona,zu
0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.028352,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0
96,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.000000,0.0,0.109308,0.119121,0.0,0.0,0.0
97,0.0,0.0,0.0,0.0,0.0,0.0,0.043998,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0
98,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0
99,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.044349,0.0,0.000000,0.000000,0.0,0.0,0.0

**Singular Value Decomposition (SVD)**

In [ ]:
# Menggunakan SVD untuk reduksi dimensi
n_components = 100
svd = TruncatedSVD(n_components=n_components)
svd_matrix = svd.fit_transform(tfidf_matrix)

# Mengubah hasil SVD menjadi DataFrame
svd_df = pd.DataFrame(svd_matrix, columns=[f'feature {i+1}' for i in range(n_components)])

# Menampilkan hasil
print("Hasil reduksi dimensi dengan SVD:")
svd_df

Hasil reduksi dimensi dengan SVD:

,feature 1,feature 2,feature 3,feature 4,feature 5,feature 6,feature 7,feature 8,feature 9,feature 10,...,feature 91,feature 92,feature 93,feature 94,feature 95,feature 96,feature 97,feature 98,feature 99,feature 100
0,0.026820,0.096547,0.054461,0.127306,-0.019552,0.001356,-0.017221,0.032739,0.077824,0.071295,...,-0.006476,-0.005238,-0.002664,-0.000142,0.001227,-0.001039,0.001803,0.000628,0.000921,0.000551
1,0.037736,0.069938,0.082272,0.100362,-0.029890,-0.009371,0.005275,0.021298,0.056487,0.036845,...,0.007466,0.002191,-0.003546,0.008039,0.013127,0.000047,0.002006,0.000832,-0.001369,0.000305
2,0.024891,0.092727,0.078429,0.145977,-0.036944,-0.030159,0.001975,0.086824,0.195100,-0.015933,...,0.003778,0.001865,0.002006,0.000197,-0.000213,0.009161,-0.000826,-0.002317,0.001368,0.000441
3,0.022522,0.089931,0.084388,0.186253,-0.042571,-0.005862,-0.005224,0.007939,-0.025849,0.221573,...,-0.001489,0.003107,-0.000582,0.001156,0.003558,0.002411,-0.000858,-0.002877,-0.000525,0.000158
4,0.026334,0.056126,0.015337,0.014987,-0.004832,-0.005398,-0.005845,0.051311,0.050742,0.012153,...,0.000982,-0.008124,0.001566,0.004282,0.001767,-0.004228,-0.000512,-0.001812,0.006122,0.000169
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0.098497,0.012899,0.234492,0.034522,0.641338,0.021421,-0.003489,-0.140954,0.058899,-0.003154,...,-0.000324,0.002534,-0.031944,0.022111,-0.001652,0.000346,0.001266,0.000948,-0.001909,0.000616
96,0.450511,-0.062944,-0.040608,-0.020799,-0.036821,0.015296,0.349185,-0.010808,0.013910,-0.016124,...,0.014635,-0.038086,-0.014922,-0.088167,-0.001593,0.001719,0.000813,-0.000567,0.000080,-0.000120
97,0.094541,0.021255,0.145756,0.022787,0.272841,0.017641,0.055395,0.294663,-0.159173,-0.162667,...,-0.119507,0.000584,-0.389434,0.050782,0.003258,-0.000960,0.011890,-0.004024,0.002781,0.000114
98,0.302910,-0.071926,-0.027539,0.012833,-0.024973,0.031176,0.344967,0.013416,0.038247,0.113966,...,-0.016751,0.022306,0.021572,0.014568,0.001410,-0.001584,-0.003865,0.001978,-0.001723,-0.000576
99,0.099199,0.028660,0.072345,-0.015318,-0.011147,-0.002078,-0.063135,0.160169,-0.095557,-0.069413,...,0.007721,-0.004926,-0.004662,-0.008920,0.012309,0.001398,-0.003351,0.012448,0.001318,-0.000634

**Implementasi**

In [ ]:
import re
import string
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import nltk
nltk.download('stopwords')
nltk.download('punkt')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [ ]:

def preprocess_text(text):
    # Cleaning: Menghapus angka dan tanda baca
    text = re.sub(r'\d+', '', text)
    text = text.translate(str.maketrans('', '', string.punctuation))
    text = text.lower()
    words = word_tokenize(text)

    # Stopword removal
    stop_words = set(stopwords.words("indonesian"))
    words = [word for word in words if word not in stop_words]

    return ' '.join(words)

def search_similar_documents(query_text, top_k=5):
    query_text = preprocess_text(query_text)

    # Transformasi query text
    query_tfidf = tfidf_vectorizer.transform([query_text])
    query_svd = svd.transform(query_tfidf)

    # Hitung jarak Euclidean antara query dan dokumen
    distances = euclidean_distances(query_svd, svd_matrix)

    # Ambil indeks dokumen terdekat
    closest_indices = np.argsort(distances[0])[:top_k]
    similarities = distances[0][closest_indices]

    return closest_indices, similarities

# Input teks dan preprocessing
query_text = input("Masukkan teks: ")
processed_query_text = preprocess_text(query_text)

# Melakukan pencarian dengan teks yang telah dipreproses
top_k = 5
indices, distances = search_similar_documents(processed_query_text, top_k)

# Menampilkan hasil pencarian
print("\nHasil pencarian untuk query:", processed_query_text)
for idx, distance in zip(indices, distances):
    print(f"Dokumen ke-{idx + 1}: {documents[idx]}")
    print(f"Jarak Euclidean: {distance:.4f}\n")

Masukkan teks: penyakit sifilis pada wanita

Hasil pencarian untuk query: penyakit sifilis wanita
Dokumen ke-1: jakarta sifilis penyakit raja singa infeksi menular seksual ims ditularkan hubungan vaginal anal oral penularan melibatkan orang terinfeksi sifilis pria berhubungan jenis senang bergantiganti pasangan jarang wanita terkena penyakit salah satunya akibat tertular pasangan seksnya dirimu mengidap penyakit raja singa temukan serangkaian gejala sifilis gejala sifilis wanita gejala sifilis wanita bervariasi berdasarkan tahapan perkembangan infeksinya dilansir cleveland clinic serangkaian gejala penyakit raja singa sifilis primer penyakit raja singa tahap primer muncul berkisar terpapar bakteri penyebabnya gejala luka kulit chancre luka pintu masuk bakteri tubuh terkadang nyeri pengidap menyadari terkena sifilis chancre terletak vagina dubur mulut luka muncul kelamin dubur mulut gejala hilang minggu penyakitnya sembuh sisi chancre parah diobati infeksi berkembang tahap fase sifilis mudah menular hubungan intim vaginal anal oral sifilis sekunder chancre hilang ruam kasar benjolan muncul tubuh telapak tangan kaki ruam gatal detikers mengalami gejala demam flu sakit tenggorokan kelelahan nyeri otot sakit kepala rambut rontok pembengkakan kelenjar getah bening gejalagejala muncul hilang berbulanbulan bertahuntahun ruam hilang terinfeksi pengobatan mencegah infeksi berkembang tahap penyakit raja singa ditularkan hubungan intim vaginal anal oral fase sekunder sifilis laten gejalagejala tahap diobati infeksi berkembang tahap fase laten penyakit raja singa memunculkan gejala infeksinya tahap merusak jantung saraf tulang organ tubuh tahap laten fase jarang penularan sifilis pasangan seks sifilis sembuh tahap laten sembuh gejala timbul minim infeksi berlanjut fase pengobatan sifilis tersier persen penyakit raja singa berkembang tahap tersier fase kesehatan serius muncul meliputi kerusakan otak demensia kesehatan kognitif penyakit jantung gangguan pergerakan otot kerusakan saraf kejang penglihatan kebutaan penyebab sifilis wanita sifilis disebabkan bakteri treponema pallidum tersebar hubungan intim anus vagina mulut luka kulit bakteri menyebar tubuh merusak organ penularan penyakit raja singa pesat pengidapnya tahap primer sekunder ditandai luka ruam bisul orang tertular menyentuh luka ruam dialami pengidap penyakit wanita hamil terkena sifilis menyebarkan penyakit janinnya detikers tertular menyentuh bendabenda bekas pengidap sifilis dudukan toilet gagang pintu perkakas disebabkan bakteri penyebab penyakit raja singa bertahan hidup benda mati aznrow
Jarak Euclidean: 0.4856

Dokumen ke-36: jakarta direktur jenderal pelayanan kesehatan kemenkes azhar jaya mengganti direktur utama rsup prof dr rd kandou manado sulawesi utara perundungan ppds program pendidikan dokter spesialis penyakit langkah diambil konsistensi kemenkes menghilangkan perundungan rumah sakit pendidikan rs kandou pembenahan total berharap bullying diberantas tuntas rs kandou ganti dirutnya ganti azhar jaya ditemui detikcom jakarta timur selasa azhar terlibat perundungan membiarkan sanksi kemenkes berharap sanksi menghilangkan budaya perundungan lingkungan kedokteran pokoknya terlibat bulling membiarkan care reshuffled dilaporkan kementerian kesehatan menghentikan program ilmu penyakit fakultas kedokteran fk sam ratulangi rsup prof dr rd kandou manado sulawesi utara dugaan perundungan pungutan liar surat tertanggal oktober berdasarkan hasil klarifikasi pengaduan program studi perundungan prodi penyakit permintaan pembayaran pungutan liar ppds peserta pendidikan dokter spesialis senior penyakit ppds junior calon ppds penyakit bunyi butir surat surat perundungan kementerian kesehatan peringatan bentuk perundungan ancaman kekerasan verbal nonverbal ppds junior knaup
Jarak Euclidean: 1.0784

Dokumen ke-26: jakarta direktur penyehatan lingkungan kesehatan kemenkes ri dr anas maruf penyakit infeksi saluran pernapasan ispa pneumonia anakanak meningkat salah pemicunya kualitas udara indonesia kian memburuk data kualitas udara polusi memburuk peningkatan penyakit ispa pneumonia anak dr anas detikcom auditorium bmkg jakarta pusat selasa data bpjs kesehatan rp triliun dibelanjakan penyakitpenyakit terkait respirasi anas perhatian masyarakat pasalnya kualitas udara buruk riskan balita lansia kelompok rentan lansia anakanak anakanak terdampak usia penyakitpenyakit terkait respirasi kemenkes penelitian terkait hubungan kualitas udara buruk penyakit kardiovaskular kanker butuh diteliti polusi udara buruk berpengaruh penyakit kardiovaskular kanker kemenkes mengajak masyarakat menjaga kualitas udara indonesia pasalnya kualitas udara membantu meningkatkan usia harapan hidup survei kesehatan indonesia ski usia harapan hidup menerus hidup kualitas udara jelek susah mencapai usia harapan hidup tutupnya dpynaf
Jarak Euclidean: 1.0899

Dokumen ke-28: jakarta tekanan darah hipertensi kondisi kali disadari kondisi berdampak serius kesehatan tekanan darah ditangani risiko penyakit jantung stroke kerusakan organ tubuh ginjal ahli jantung new yorkpresbyteriancolumbia university irving medical center marwah abdalla md mph salah menurunkan tekanan darah diet dash dietary approaches to stop hypertension diet dirancang khusus membantu mengelola tekanan darah menekankan konsumsi buah sayur produk susu rendah lemak makanan kaya serat diet dash menyehatkan jantung kaya makanan memiliki kandungan kalsium magnesium kalium protein serat marwah dikutip laman prevention penurun darah alami cepat pisang pisang salah buah kaya kalium pisang berukuran mengandung mg nutrisi setara persen asupan harian direkomendasikan kalium mengelola tekanan darah pisang kaya serat bawang putih national institute of health nih senyawa allicin bawang putih membantu mengurangi tekanan darah allicin dilepaskan bawang putih dihancurkan dicincang dokter merekomendasikan penggunaan suplemen bawang putih penelitian efektivitasnya hipertensi terbatas mengkonsumsinya olesan bawang putih dipanggang minyak zaitun ubi jalar ubi jalar kaya kalium magnesium diet penurun tekanan darah makanan kaya serat jantung oatmeal bijibijian utuh berserat oatmeal dikaitkan penurunan risiko penyakit kardiovaskular membantu menurunkan berat badan kadar kolesterol penelitian porsi bijibijian utuh sehari menurunkan risiko penyakit jantung persen oatmeal sarapan bagus bijibijian utuh alpukat buah alpukat lembut sumber kalsium magnesium kalium membantu menurunkan angka tekanan darah alpukat mengandung mg kalium persen asupan harian brokoli brokoli memiliki senyawa ajaib membantu menurunkan tekanan darah kalsium kalium magnesium vitamin c penelitian pola makan brokoli tingkat penyakit jantung rendah meningkatkan umur bit buah bit kaya oksida nitrat menurunkan tekanan darah penelitian minum jus bit membantu menurunkan tekanan darah sistolik mmhg cobalah jus bit pola diet membeli jus dibeli toko pastikan gula tambahan paprika merah paprika merah membantu menurunkan tekanan darah kaya kalium vitamin a kaya serat vitamin c menjadikannya camilan sehat dipanggang tambahan minyak zaitun yogurt rendah lemak bebas lemak produk susu rendah lemak sumber kalsium salah senyawa utama membantu melawan tekanan darah kalium protein vitamin mineral yogurt melengkapi diet porsi yogurt rendah lemak seberat ons persen kalsium direkomendasikan minyak zaitun minyak zaitun kalori memiliki manfaat kesehatan minyak zaitun kaya polifenol dikaitkan penurunan tekanan darah kalangan wanita penelitian mengganti mentega minyak zaitun memasak mengurangi risiko penyakit kematian mengonsumsi minyak zaitun menurunkan risiko kematian terkait demensia saonaf
Jarak Euclidean: 1.1018

Dokumen ke-19: jakarta kementerian kesehatan kesejahteraan korea selatan barubaru penghargaan wanita melahirkan anak salah satunya aktris nam bora eom gyesuk dianugerahi medali seongnyu penghargaan tingkat order of civil merit berkontribusi negara prestasi bidang politik ekonomi masyarakat pendidikan akademis melahirkan putra delapan putri hamil melahirkan kesulitan berkat anakanak tumbuh memiliki momen bahagia upacara penghargaan glad hotel yeouido seoul oktober acara memperingati hamil tahunan eom menekankan melahirkan membesarkan anak ceramah bukunya kisah keluarganya diterbitkannya sembilan anakanaknya tua memiliki pekerjaan kuliah sekolah menengah lee yeongmi korea penghargaan upacara anak menerima medali jasa sipil orangorang berkontribusi negara prestasi sumbangan mempertaruhkan nyawa menyelamatkan orang mengabdikan hidup pelayanan publik lee melahirkan kali usia membesarkan anakanaknya berkontribusi sektor masyarakat anaknya terkenal aktris nam bora anakanak seniman karyawan bank peneliti ahli kesehatan gigi termuda sekolah menengah dibandingkan an an melahirkan membesarkan anakanak kebijakan mendukung persalinan pengasuhan anak mendengar orangorang kekurangannya membutuhkan budaya kerja orang cuti mengasuh anak khawatir dipikirkan orang dukungan pekerja mandiri memiliki cuti mengasuh anak mengambil cuti pekerjaan tingkat kesuburan korea selatan anak dimiliki wanita hidupnya mencapai rekor terendah triwulanan triwulan angka diproyeksikan turun titik terendah knakna
Jarak Euclidean: 1.1026